import Head from "next/head";
import React, { useState, useEffect } from 'react';
import Header from "@/components/Header";
import styles from './../styles/Contact.module.css'


export default function Contact() {

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Header />
        <div >
        <iframe  src="https://docs.google.com/forms/d/e/1FAIpQLSdrRQc5-EdIqNJ2hMmIbJmaiXRVbJXiZ7GMY6tccJl_I1zBtA/viewform?embedded=true" width="100%" height="603">読み込んでいます…</iframe>
        </div>
        </main>
      </>
    );
}
