import Head from "next/head";
import styles from "./../styles/Home.module.css";
import Header from "./../components/Header";
import React, { useState, useEffect } from 'react';
import Block from "@/components/Block";

type Analize = {
  id: number,
  text1: string,
  text2: string,
  text3: string
}

export default function Storage() {
  const [analize, setAnalize] = useState<Analize[]>([]);
  useEffect(() => {
    const storedTodos = JSON.parse(localStorage.getItem('analize') || '[]') as Analize[];
    if (storedTodos) {
      setAnalize(storedTodos);
    }
  }, []);

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className={styles.progressbar}></div>
          <Header />
          <div className="">
            <h1>履歴一覧</h1>
            <Block text1="f;jasklfawl;fjawf" text2="f;jasklfawl;fjawf" text3="f;jasklfawl;fjawf" />
            <ul>
            {analize.map((analize) => (
                <li key={analize.id}>
                  <Block text1={analize.text1} text2={analize.text2} text3={analize.text3} />
                </li>
              ))}
            </ul>
          </div>
        </main>
      </>
    );
}
